name: flybis
description: A TecWolf Project Using Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase: ^7.2.0 # WEB

  firebase_core: ^0.4.3+1 # ANDROID IOS WEB
  firebase_auth: ^0.15.3 # ANDROID IOS WEB

  firebase_storage: ^3.1.0 # ANDROID IOS
  cloud_firestore: ^0.13.0+1 # ANDROID IOS
  cloud_functions: ^0.4.1+6 # ANDROID IOS

  firebase_dynamic_links: ^0.5.0+9 # ANDROID IOS
  firebase_messaging: ^6.0.9 # ANDROID IOS
  firebase_in_app_messaging: ^0.1.1+1 # ANDROID IOS

  firebase_performance: ^0.3.1+5 # ANDROID IOS
  firebase_crashlytics: ^0.1.2+3 # ANDROID IOS
  firebase_analytics: ^5.0.9 # ANDROID IOS
  firebase_admob: ^0.9.0+10 # ANDROID IOS

  firebase_ml_vision: ^0.9.3+5 # ANDROID IOS
  # Firebase - End
  
  giphy_picker: ^1.0.4

  image_picker: ^0.6.2+3 # ANDROID IOS
  geolocator: ^5.1.5 # ANDROID IOS
  uuid: ^2.0.4 # ANDROID IOS WEB
  image: ^2.1.11 # ANDROID IOS WEB
  animator: ^1.0.0+3 # ANDROID IOS WEB
  cupertino_icons: ^0.1.3
  path_provider: ^1.5.1 # ANDROID IOS
  timeago: ^2.0.22 # ANDROID IOS WEB
  cached_network_image: ^2.0.0-rc # ANDROID IOS

  flutter_svg: ^0.15.0 # ANDROID IOS
  flutter_html: ^0.11.0 # ANDROID IOS WEB

  flutter_feather_icons: ^1.0.3 # UNDEFINED

  provider: ^3.2.0 # ANDROID IOS WEB

  bubble_bottom_bar: ^1.2.0 # ANDROID IOS WEB

  #story_view: ^0.11.0 # ANDROID IOS

  share: ^0.6.3+5 # ANDROID IOS
  url_launcher: ^5.4.1 # ANDROID IOS WEB
  connectivity: ^0.4.6+1 # ANDROID IOS

  video_player: ^0.10.5 # ANDROID IOS
  video_player_web: ^0.1.1+1 # WEB
  chewie: ^0.9.8 # ANDROID IOS

  path: ^1.6.4 # ANDROID IOS WEB
  async: ^2.4.0
  camera: ^0.5.7+2 # ANDROID IOS

  transparent_image: ^1.0.0 # ANDROID IOS WEB

  flutter_staggered_grid_view: ^0.3.0 # ANDROID IOS WEB
  flutter_pagewise: ^1.2.3
  flutter_phoenix: ^0.1.0 # ANDROID IOS WEB

  bottom_navy_bar: ^5.3.2
  gradient_bottom_navigation_bar: ^1.0.0+4

  line_awesome_icons: ^1.0.4+2
    
  intl: ^0.16.1
    
  #flutter_unity_widget: ^0.1.6+5
  
  incrementally_loading_listview: ^0.3.0
  
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  photo_view: ^0.9.1

  e3kit:
    git:
      url: git://github.com/cardoso/virgil-e3kit-flutter.git
  
  native_admob:
    path: ./lib/packages/native_admob

dev_dependencies:
  #flutter_test:
    #sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/flybis.png"
  image_path_android: "assets/icons/flybis.png"
  #adaptive_icon_background: "assets/icons/background.png"
  #adaptive_icon_foreground: "assets/icons/foreground.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Matiz
      fonts:
        - asset: assets/fonts/Matiz.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Hairline.ttf
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
    - family: Lato-Italic
      fonts:
        - asset: assets/fonts/Lato/Lato-Italic.ttf
    - family: Lato-Heavy
      fonts:
        - asset: assets/fonts/Lato/Lato-Heavy.ttf

  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg

module:
  androidX: true
